install:
	pip3 install sounddevice --break-system-packages
	pip3 install scipy --break-system-packages
	pip3 install pydub --break-system-packages
	pip3 install pillow --break-system-packages
	pip3 install ffmpeg --break-system-packages
	sudo apt-get -y install portaudio19-dev
	sudo apt install -y python3-tk
	sudo apt-get install -y ffmpeg







